name = "werewolf"
account_id = "2c42f4960f9c28a9235cac01483bd626"
main = "apps/api/src/index.ts"
compatibility_date = "2025-09-17"
compatibility_flags = ["nodejs_compat"]

[vars]
ENV = "development"

[[durable_objects.bindings]]
name = "werewolf-contest-room"
class_name = "ContestRoom"

[[migrations]]
tag = "v1"
new_classes = [ "ContestRoom" ]


[[migrations]]
tag = "v2"

[[d1_databases]]
binding = "DB"
database_name = "werewolf-d1-dev"
database_id = "952d9b14-6236-4e59-8fc8-66b2df9128b7"
migrations_dir = "./migrations"

[[kv_namespaces]]
binding = "KV"
id = "8cf514e5365c468eb782d0a96f6ad309"

[env.production]
name = "werewolf"
workers_dev = true

[env.production.vars]
ENV = "production"

[[env.production.durable_objects.bindings]]
name = "werewolf-contest-room"
class_name = "ContestRoom"

[[env.production.d1_databases]]
binding = "DB"
database_name = "werewolf-d1"
database_id = "4e260168-4bc5-455a-a1e8-b9aa43844004"
migrations_dir = "./migrations"

[[env.production.kv_namespaces]]
binding = "KV"
id = "0a529ddf9e174436a1353b74867ea4d8"
